route = "./"
imagenes_cortadas = route+"imagenes_cortadas/"
archivo_catalogo = route+"datos_astrometria_modificados/datos_gaia3edr.csv" 
bash_scripts = route+"bash_scripts/"
csv_out = route+"csv_out/"
fits_out = route+"fits_out/"
imagenes = route+"imagenes/"